spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sampledeliverytest?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: nT5A9Ln!TT.F*8Bv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  data:
    rest:
      base-path: /api
  logging:
    level:
      root: ERROR
      org.springframework.web: DEBUG
      org.hibernate: ERROR
